spin_manifest_version = "1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
description = "Demo app to receive MQTT messages."
name = "mqtt-app"
trigger = { type = "mqtt", address = "mqtt://172.17.0.2:1883", username = "user", password = "password", keep_alive_interval = "30" }
version = "0.1.0"

# This spin app has two components mqtt-c01 and mqtt-c02, which subscribe to the two different topics from the single MQTT server.
[[component]]
id = "mqtt-c01"
source = "target/wasm32-wasi/release/mqtt_app.wasm"
allowed_outbound_hosts = ["mqtt://172.17.0.2:1883"]
[component.trigger]
topic = "messages-in01"
qos = "1"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "mqtt-c02"
source = "target/wasm32-wasi/release/mqtt_app.wasm"
allowed_outbound_hosts = ["mqtt://172.17.0.2:1883"]
[component.trigger]
topic = "messages-in02"
qos = "0"
[component.build]
command = "cargo build --target wasm32-wasi --release"
