# TODO: Add support for int for some parameters below and wit file copy.
manifest_version = "1"
id = "mqtt-rust"
description = "Mqtt message handler/trigger using Rust."
tags = ["mqtt", "rust"]

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
mqtt-address = { type = "string", prompt = "Mqtt Address", default = "mqtt://localhost:1883" }
mqtt-username = { type = "string", prompt = "Mqtt Username", default = "" }
mqtt-password = { type = "string", prompt = "Mqtt Password", default = "" }
mqtt-keep_alive_interval = { type = "string", prompt = "Mqtt Keep Alive Interval (Secs)", default = "30" }
mqtt-topic = { type = "string", prompt = "Mqtt Topic" }
mqtt-qos = { type = "string", prompt = "Mqtt QoS for Topic", default = "1"}
