spin_manifest_version = "1"
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
trigger = { type = "mqtt", address = "{{mqtt-address}}", username = "{{mqtt-username}}", password = "{{mqtt-password}}", keep_alive_interval = "{{mqtt-keep_alive_interval}}" }
version = "0.1.0"

[[component]]
id = "{{project-name | kebab_case}}"
source = "target/wasm32-wasi/release/{{project-name | snake_case}}.wasm"
allowed_outbound_hosts = ["{{mqtt-address}}"]
[component.trigger]
topic = "{{mqtt-topic}}"
qos = "{{mqtt-qos}}"
[component.build]
command = "cargo build --target wasm32-wasi --release"
